# Application name
spring.application.name=expense

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/expense?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=N@rayani12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf (optional, but good for debugging)
spring.thymeleaf.cache=false
